feat(api): respond with proper codes, errors
"I understand it, now."

Condense often repeated error prefixes into underlying functions.

Return status codes according to the following:

StatusOK: when returning any body on a successful operation.

StatusNoContent: When a delete or update is successful, and do not need to return a response body.

StatusForbidden: When a user does not have role clearance for an action.

StatusUnauthorized: When a client inputs the wrong credentials for login, or presents an invalid JWT.

StatusBadRequest: When any URI or query parameter, or payload field is invalid for a handler operation.

StatusInternalServerError: When a server fails to run a database operation, while user input(s) are all otherwise valid. OR, when the server cannot get multiple of some class of resource.

StatusNotFound: When an otherwise valid operation on a single resource fails.